language: objective-c
before_script:
  - brew update
  - brew upgrade xctool || true
script:
  - xctool -project WebViewJavascriptBridge.xcodeproj -scheme WebViewJavascriptBridge -configuration Release -sdk iphonesimulator test
